[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build", "pnpm prisma generate"]

[start]
cmd = "pnpm prisma migrate deploy && node dist/index.js"

